apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: default   # namespace where the cronjob will be deployed
spec:
  schedule: "*/2 * * * *"   # this runs the container every 5 minutes you can change this to any time you want.
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          volumes:
          - name: script
            configMap:
              name: backup-script
              defaultMode: 0777
          containers:
            - name: db-backup
              image: test:v5
              volumeMounts:
              - name: script
                mountPath: /test
              command: ["/bin/sh"] #, "-c", "/test/backup_script.sh"]       #command to run when container starts
              args: ["-c", "/test/backup_script.sh"]
              imagePullPolicy: IfNotPresent
              env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: backup-secrets
                    key: aws-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: backup-secrets
                    key: aws-secret
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: backup-secrets
                    key: mongo-uri
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  configMapKeyRef:
                    name: backup-configmap
                    key: region
              - name: S3_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: backup-configmap
                    key: s3-bucket
              - name: DBS
                valueFrom:
                  configMapKeyRef:
                    name: backup-configmap
                    key: collections
              - name: excludeCollections 
                valueFrom:
                  configMapKeyRef:
                    name: backup-configmap
                    key: excludes
          restartPolicy: Never
